version: "3"

services:
  backend:
    env_file: "./backend/.env"
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: "hyunsujk/fishtech-backend"
    ports:
      - "5000:5000"
  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: "hyunsujk/fistech-frontend"
    ports:
      - "3000:3000"
    links:
      - "backend"
